### ISSUE TITLE
Use via Docker (not Kubernetes)?

### ISSUE THREAD

**Issue by prologic** [NativeCI/gluster-heketi-csi-driver#1]
It should be possible to `docker plugin install ...` this CSI driver right?

The only thing I _think_ you need to do is publish a version of this to the [Docker Hub](https://hub.docker.com)

Can we do this?

**Comment by prologic** [comment]
Actually... I'm not even sure if Docker / Docker Swarm can even load up CSI drivers? 🤔

**Comment by paladium** [comment]
Hello, yes you are right, docker does not support CSI drivers :(
The image is being published here if you are still interested in using it - https://hub.docker.com/r/dragma/gluster-heketi-csi-driver
